### ISSUE TITLE
[BUG] - Error when retrieving credentials from container-role - destroyteams

### ISSUE THREAD

**Issue by rb201** [awslabs/aws-orbit-workbench#1032]
**Describe the bug**
Destroy teams fails after destroying resources/namespaces. In my observation, this seems to happen in a destroy where the env has had more activity, and therefore more stuff to delete.

[destroy.py   : 85] Destroyed all lake-admin resources using thread Thread-1
[ Error ] CredentialRetrievalError: Error when retrieving credentials from container-role: Error retrieving metadata: Received error when attempting to retrieve ECS metadata: Could not connect to the endpoint URL: "http://169.254.170.2/v2/credentials/f014f115-c05c-4e7e-84ec-d820da7bbc02"

Full trace:
Error Traceback:
Traceback (most recent call last):
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/botocore/httpsession.py", line 323, in send
    urllib_response = conn.urlopen(
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 507, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/botocore/awsrequest.py", line 92, in _send_request
    rval = super(AWSConnection, self)._send_request(
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/botocore/awsrequest.py", line 120, in _send_output
    self.send(msg)
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/botocore/awsrequest.py", line 204, in send
    return super(AWSConnection, self).send(str)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPConnection object at 0x7f375ab45910>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/botocore/utils.py", line 2255, in _get_response
    response = self._session.send(request.prepare())
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/botocore/httpsession.py", line 352, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://169.254.170.2/v2/credentials/f014f115-c05c-4e7e-84ec-d820da7bbc02"

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/botocore/credentials.py", line 1870, in fetch_creds
    response = self._fetcher.retrieve_full_uri(
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/botocore/utils.py", line 2205, in retrieve_full_uri
    return self._retrieve_credentials(full_url, headers)
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/botocore/utils.py", line 2241, in _retrieve_credentials
    return self._get_response(
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/botocore/utils.py", line 2273, in _get_response
    raise MetadataRetrievalError(error_msg=error_msg)
botocore.exceptions.MetadataRetrievalError: Error retrieving metadata: Received error when attempting to retrieve ECS metadata: Could not connect to the endpoint URL: "http://169.254.170.2/v2/credentials/f014f115-c05c-4e7e-84ec-d820da7bbc02"

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/codebuild/output/src689/src/s3/01/cli/.venv/bin/orbit", line 8, in <module>
    sys.exit(main())
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/aws_orbit/__main__.py", line 907, in main
    cli()
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/aws_orbit/__main__.py", line 362, in destroy_teams
    destroy_commands.destroy_teams(env=env, debug=debug)
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/aws_orbit/commands/destroy.py", line 85, in destroy_teams
    remote.run(
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/aws_orbit/remote.py", line 105, in run
    _execute_codebuild(
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/aws_orbit/remote.py", line 83, in _execute_codebuild
    _wait_execution(
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/aws_orbit/remote.py", line 42, in _wait_execution
    for status in codebuild.wait(build_id=build_id):
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/aws_orbit/services/codebuild.py", line 213, in wait
    build = fetch_build_info(build_id=build_id)
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/aws_orbit/services/codebuild.py", line 168, in fetch_build_info
    client = boto3_client("codebuild")
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/aws_orbit/utils.py", line 50, in boto3_client
    return boto3.Session().client(service_name=service_name, use_ssl=True, config=get_botocore_config())
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/boto3/session.py", line 258, in client
    return self._session.create_client(
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/botocore/session.py", line 839, in create_client
    credentials = self.get_credentials()
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/botocore/session.py", line 441, in get_credentials
    self._credentials = self._components.get_component(
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/botocore/credentials.py", line 1977, in load_credentials
    creds = provider.load()
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/botocore/credentials.py", line 1840, in load
    return self._retrieve_or_fail()
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/botocore/credentials.py", line 1849, in _retrieve_or_fail
    creds = fetcher()
  File "/codebuild/output/src689/src/s3/01/cli/.venv/lib/python3.8/site-packages/botocore/credentials.py", line 1875, in fetch_creds
    raise CredentialRetrievalError(provider=self.METHOD,
botocore.exceptions.CredentialRetrievalError: Error when retrieving credentials from container-role: Error retrieving metadata: Received error when attempting to retrieve ECS metadata: Could not connect to the endpoint URL: "http://169.254.170.2/v2/credentials/f014f115-c05c-4e7e-84ec-d820da7bbc02"

**Comment by srinivasreddych** [comment]
This happens in a scenario when codebuild times out. Pls raise the build time out
