### ISSUE TITLE
Pod IAM Role session not updating

### ISSUE THREAD

**Issue by srinivasreddych** [awslabs/aws-orbit-workbench#708]
When running the regression notebooks, we are seeing error of pattern:

WARNING:botocore.credentials:Refreshing temporary credentials failed during mandatory refresh period.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/botocore/credentials.py", line 529, in _protected_refresh
    metadata = self._refresh_using()
  File "/opt/conda/lib/python3.8/site-packages/botocore/credentials.py", line 670, in fetch_credentials
    return self._get_cached_credentials()
  File "/opt/conda/lib/python3.8/site-packages/botocore/credentials.py", line 680, in _get_cached_credentials
    response = self._get_credentials()
  File "/opt/conda/lib/python3.8/site-packages/botocore/credentials.py", line 890, in _get_credentials
    return client.assume_role_with_web_identity(**kwargs)
  File "/opt/conda/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ExpiredTokenException: An error occurred (ExpiredTokenException) when calling the AssumeRoleWithWebIdentity operation: Token expired: current date/time 1624483774 must be before the expiration date/time1624292956

**Comment by srinivasreddych** [comment]
$ kubectl get pods -n lake-creator
NAME                           READY   STATUS             RESTARTS   AGE
chmod-fsx-pod                  0/1     CrashLoopBackOff   2192       7d18h
clean-regression-files-dt66z   1/1     Running            0          7d9h
copy-regression-data-r5t6n     0/1     Completed          0          7d9h
copy-sample-code-b6h8f         0/1     Completed          0          7d8h
efs-init-lake-creator-k4s9g    0/1     Completed          0          7d9h
