### ISSUE TITLE
Jupyterlab_orbit fails to build sdist, wheel

### ISSUE THREAD

**Issue by rb201** [awslabs/aws-orbit-workbench#774]
`jlpm` unavailable.  If you're running this command using sudo, make sure `jlpm` is available to sudo
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    "Framework :: Jupyter",
  File "/codebuild/output/src651/src/s3/00/.venv/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/codebuild/output/src651/src/s3/00/.venv/lib/python3.7/site-packages/jupyter_packaging/setupbase.py", line 503, in run
    [self.run_command(cmd) for cmd in cmds]
  File "/codebuild/output/src651/src/s3/00/.venv/lib/python3.7/site-packages/jupyter_packaging/setupbase.py", line 503, in <listcomp>
    [self.run_command(cmd) for cmd in cmds]
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/codebuild/output/src651/src/s3/00/.venv/lib/python3.7/site-packages/jupyter_packaging/setupbase.py", line 424, in run
    self.command.run()
  File "/codebuild/output/src651/src/s3/00/.venv/lib/python3.7/site-packages/jupyter_packaging/setupbase.py", line 274, in run
    c.run()
  File "/codebuild/output/src651/src/s3/00/.venv/lib/python3.7/site-packages/jupyter_packaging/setupbase.py", line 401, in run
    raise ValueError(('missing files: %s' % missing))
ValueError: missing files: ['/codebuild/output/src651/src/s3/01/jupyterlab_orbit/jupyterlab_orbit/labextension/package.json']

Source archive
tar (child): dist/*tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by rb201** [comment]
https://github.com/awslabs/aws-orbit-workbench/pull/793
